package com.asafjac.jbplugins.demodriver

import com.intellij.notification.NotificationType
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.openapi.fileEditor.FileEditorManagerListener
import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.ProjectRootManager
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.psi.PsiDocumentManager
import com.intellij.ui.JBColor
import com.intellij.ui.components.JBCheckBox
import com.intellij.ui.components.JBLabel
import com.intellij.ui.components.JBList
import com.intellij.ui.components.JBScrollPane
import com.intellij.util.ui.JBUI
import java.awt.BorderLayout
import java.awt.Dimension
import java.awt.FlowLayout
import java.awt.GridBagConstraints
import java.awt.GridBagLayout
import java.awt.Insets
import javax.swing.BorderFactory
import javax.swing.Box
import javax.swing.DefaultListModel
import javax.swing.JButton
import javax.swing.JComboBox
import javax.swing.JPanel
import javax.swing.JSpinner
import javax.swing.JTextField
import javax.swing.SpinnerNumberModel
import javax.swing.SwingConstants

/**
 * The Demo Driver panel: pick a tape, see its steps, adjust the framing, run it.
 *
 * Every control writes one `Set` line into the tape file itself rather than holding state of its
 * own. That is the whole design: the file stays the only source of truth, so a tape written by
 * hand or generated by a script is exactly as first-class as one configured here, and the panel
 * is a view rather than an owner.
 */
class DemoDriverPanel(private val project: Project) : JPanel(BorderLayout()) {

    private val tapes = JComboBox<String>()
    private val steps = DefaultListModel<String>()
    private val stepList = JBList(steps)
    private val status = JBLabel(" ")

    private val cropMode = JComboBox(CROP_MODES)
    private val cropArg = JTextField(14)
    private val padding = JSpinner(SpinnerNumberModel(0, 0, 400, 8))
    private val width = JSpinner(SpinnerNumberModel(940, 320, 3840, 20))
    private val framerate = JSpinner(SpinnerNumberModel(10, 1, 60, 1))
    private val cursor = JBCheckBox("Show pointer", true)
    private val tooltips = JBCheckBox("Allow hover tooltips", true)
    private val snap = JBCheckBox("Snap region to IDE parts", false)

    private val runButton = JButton("Run and capture")
    private val recordButton = JButton("Record")
    private val stopButton = JButton("Stop").apply { isEnabled = false }
    private val reload = JButton("Reload")
    private val recorder = TapeRecorder(project)

    private val stepDuration = JSpinner(SpinnerNumberModel(700, 0, 60000, 100))
    private val stepText = JTextField(12)
    private val stepLine = JSpinner(SpinnerNumberModel(0, 0, 100000, 1))
    private val stepKind = JComboBox(STEP_KINDS)
    private val applyStep = JButton("Apply")
    private val addStep = JButton("Add")
    private val upStep = JButton("Up")
    private val downStep = JButton("Down")
    private val dupStep = JButton("Duplicate")
    private val delStep = JButton("Delete")

    /** The tape as last parsed, so a selected row maps back to the line that produced it. */
    private var parsed: Tape? = null
    private var tapeFiles: List<VirtualFile> = emptyList()
    /** Guards the listeners while the UI is being populated from a file. */
    private var loading = false

    init {
        border = JBUI.Borders.empty(6)
        add(header(), BorderLayout.NORTH)
        add(body(), BorderLayout.CENTER)
        add(footer(), BorderLayout.SOUTH)

        wireListeners()
        refreshTapes()

        // Following the selected editor means opening a tape shows it here, which is how someone
        // arrives at this panel in the first place.
        project.messageBus.connect().subscribe(
            FileEditorManagerListener.FILE_EDITOR_MANAGER,
            object : FileEditorManagerListener {
                override fun selectionChanged(event: com.intellij.openapi.fileEditor.FileEditorManagerEvent) {
                    val file = event.newFile ?: return
                    if (file.extension == "tape") selectTape(file)
                }
            })
    }

    private fun header(): JPanel = JPanel(FlowLayout(FlowLayout.LEFT, 6, 2)).apply {
        add(JBLabel("Tape:"))
        add(tapes)
        add(reload)
    }

    private fun body(): JPanel = JPanel(BorderLayout(8, 0)).apply {
        stepList.emptyText.text = "No steps. Record one, or add them to the tape file."
        stepList.selectionMode = javax.swing.ListSelectionModel.SINGLE_SELECTION
        val left = JPanel(BorderLayout()).apply {
            add(JBScrollPane(stepList).apply { preferredSize = Dimension(300, 200) }, BorderLayout.CENTER)
            add(stepEditor(), BorderLayout.SOUTH)
        }
        add(left, BorderLayout.CENTER)
        add(framing(), BorderLayout.EAST)
    }

    /**
     * Edits the selected step in place.
     *
     * A field per thing a step can carry, rather than a raw line editor: the commonest change by
     * far is a duration that was wrong when performed live, and a spinner makes that a nudge
     * instead of retyping a line of syntax. Every edit still lands in the file as tape source.
     */
    private fun stepEditor(): JPanel {
        val fields = JPanel(FlowLayout(FlowLayout.LEFT, 4, 2)).apply {
            add(JBLabel("Command"))
            add(stepKind)
            add(JBLabel("Duration ms"))
            add(stepDuration)
            add(JBLabel("Line"))
            add(stepLine)
            add(JBLabel("Text"))
            add(stepText)
            add(applyStep)
        }
        val buttons = JPanel(FlowLayout(FlowLayout.LEFT, 4, 2)).apply {
            add(addStep); add(upStep); add(downStep); add(dupStep); add(delStep)
        }
        return JPanel(BorderLayout()).apply {
            border = BorderFactory.createTitledBorder("Selected step")
            add(fields, BorderLayout.NORTH)
            add(buttons, BorderLayout.SOUTH)
        }
    }

    private fun framing(): JPanel {
        val grid = JPanel(GridBagLayout())
        grid.border = BorderFactory.createTitledBorder("Framing")
        val c = GridBagConstraints().apply {
            insets = Insets(2, 4, 2, 4)
            anchor = GridBagConstraints.WEST
            fill = GridBagConstraints.HORIZONTAL
        }

        fun row(y: Int, label: String, field: javax.swing.JComponent) {
            c.gridx = 0; c.gridy = y; c.weightx = 0.0
            grid.add(JBLabel(label), c)
            c.gridx = 1; c.weightx = 1.0
            grid.add(field, c)
        }

        row(0, "Crop", cropMode)
        // One field for whatever the mode needs: a component name, a region, a follow size. The
        // hint text changes with the mode so it is never ambiguous what belongs here.
        row(1, "Argument", cropArg)
        row(2, "Padding", padding)
        row(3, "Width", width)
        row(4, "Framerate", framerate)

        c.gridx = 0; c.gridy = 5; c.gridwidth = 2
        grid.add(cursor, c)
        c.gridy = 6
        grid.add(tooltips.apply {
            toolTipText = "Off stops the replay's own pointer raising quick documentation " +
                "that was never in the recording"
        }, c)
        c.gridy = 7
        grid.add(snap, c)
        c.gridy = 8
        grid.add(JBLabel("Each control writes one Set line into the tape.").apply {
            foreground = JBColor.GRAY
        }, c)

        return JPanel(BorderLayout()).apply {
            add(grid, BorderLayout.NORTH)
            preferredSize = Dimension(340, 200)
        }
    }

    private fun footer(): JPanel = JPanel(BorderLayout()).apply {
        val left = JPanel(FlowLayout(FlowLayout.LEFT, 6, 2)).apply {
            add(runButton)
            add(recordButton)
            add(stopButton)
            add(Box.createHorizontalStrut(4))
            add(status.apply { horizontalAlignment = SwingConstants.LEFT })
        }
        add(left, BorderLayout.WEST)
    }

    private fun wireListeners() {
        reload.addActionListener { refreshTapes() }
        recordButton.addActionListener { startRecording() }
        stopButton.addActionListener { stopRecording() }
        tapes.addActionListener { if (!loading) load() }
        runButton.addActionListener { run() }

        stepList.addListSelectionListener { if (!loading) showSelectedStep() }
        applyStep.addActionListener { applySelectedStep() }
        addStep.addActionListener { addNewStep() }
        stepKind.addActionListener { if (!loading) showFieldsFor(stepKind.selectedItem as String) }
        upStep.addActionListener { moveSelected(-1) }
        downStep.addActionListener { moveSelected(1) }
        dupStep.addActionListener { editTape { text, line -> TapeWriter.duplicateStep(text, line) } }
        delStep.addActionListener { editTape { text, line -> TapeWriter.removeStep(text, line) } }

        cropMode.addActionListener {
            if (loading) return@addActionListener
            cropArg.toolTipText = ARG_HINTS[cropMode.selectedItem]
            cropArg.isEnabled = cropMode.selectedItem in MODES_WITH_ARG
            save()
        }
        listOf(padding, width, framerate).forEach { spinner ->
            spinner.addChangeListener { if (!loading) save() }
        }
        listOf(cursor, tooltips, snap).forEach { box -> box.addActionListener { if (!loading) save() } }
        cropArg.addActionListener { if (!loading) save() }
        cropArg.addFocusListener(object : java.awt.event.FocusAdapter() {
            override fun focusLost(e: java.awt.event.FocusEvent) { if (!loading) save() }
        })
    }

    /** Every `.tape` under the project's content roots. */
    private fun refreshTapes() {
        val found = mutableListOf<VirtualFile>()
        ProjectRootManager.getInstance(project).contentRoots.forEach { root ->
            com.intellij.openapi.vfs.VfsUtilCore.iterateChildrenRecursively(
                root,
                { it.isDirectory || it.extension == "tape" },
                { file ->
                    if (!file.isDirectory && file.extension == "tape") found += file
                    true
                })
        }
        tapeFiles = found.sortedBy { it.path }

        loading = true
        tapes.removeAllItems()
        tapeFiles.forEach { tapes.addItem(relativePath(it)) }
        loading = false

        if (tapeFiles.isEmpty()) {
            steps.clear()
            setStatus("No .tape files in this project.")
        } else {
            load()
        }
    }

    private fun relativePath(file: VirtualFile): String {
        val base = project.basePath ?: return file.name
        return file.path.removePrefix("$base/")
    }

    private fun selectTape(file: VirtualFile) {
        val index = tapeFiles.indexOf(file)
        if (index < 0) { refreshTapes(); return }
        if (tapes.selectedIndex != index) {
            loading = true
            tapes.selectedIndex = index
            loading = false
            load()
        }
    }

    private fun currentFile(): VirtualFile? = tapeFiles.getOrNull(tapes.selectedIndex)

    private fun currentText(): String? {
        val file = currentFile() ?: return null
        return String(file.contentsToByteArray(), Charsets.UTF_8)
    }

    /** Reads the tape and mirrors it into the controls. */
    private fun load() {
        val text = currentText() ?: return
        val tape = try {
            TapeParser.parse(text)
        } catch (e: Exception) {
            steps.clear()
            setStatus("Cannot read tape: ${e.message}", error = true)
            return
        }

        parsed = tape
        loading = true
        val previous = stepList.selectedIndex
        steps.clear()
        tape.steps.forEachIndexed { index, step ->
            steps.addElement("%2d  %s".format(index + 1, TapeRunner.describe(step)))
        }
        // Keep the selection across a reload, so a run of small edits does not need re-selecting.
        if (previous in 0 until steps.size) stepList.selectedIndex = previous

        val settings = tape.settings
        cropMode.selectedItem = when (val crop = settings.crop) {
            is Crop.Window -> "window"
            is Crop.Editor -> "editor"
            is Crop.Fit -> "fit"
            is Crop.Component -> "component"
            is Crop.Region -> "region"
            is Crop.Follow -> if (crop.what == "caret") "follow caret" else "follow mouse"
        }
        cropArg.text = when (val crop = settings.crop) {
            is Crop.Component -> crop.name
            is Crop.Region -> "${crop.x},${crop.y} ${crop.width}x${crop.height}"
            is Crop.Follow -> "${crop.width}x${crop.height} ease ${crop.easeMs}ms"
            else -> ""
        }
        cropArg.isEnabled = cropMode.selectedItem in MODES_WITH_ARG
        cropArg.toolTipText = ARG_HINTS[cropMode.selectedItem]
        padding.value = settings.padding
        width.value = settings.width
        framerate.value = settings.framerate
        cursor.isSelected = settings.cursor
        tooltips.isSelected = settings.tooltips
        snap.isSelected = settings.snap
        loading = false

        val outputs = if (settings.outputs.isEmpty()) "no Output, so nothing is captured"
        else settings.outputs.joinToString(", ")
        setStatus("${tape.steps.size} steps; $outputs")
    }

    /** Mirrors the selected step into the step fields. */
    private fun showSelectedStep() {
        val step = selectedStep() ?: return
        loading = true
        stepKind.selectedItem = kindOf(step)
        when (step) {
            is Step.Sleep -> stepDuration.value = step.ms
            is Step.Glide -> stepDuration.value = step.ms
            is Step.WaitFor -> stepDuration.value = step.ms
            else -> Unit
        }
        stepLine.value = when (step) {
            is Step.Caret -> step.line
            is Step.Select -> step.line
            is Step.Scroll -> step.line
            else -> 0
        }
        stepText.text = when (step) {
            is Step.Caret -> if (step.nth > 1) "${step.anchor} nth ${step.nth}" else step.anchor
            is Step.Select -> if (step.nth > 1) "${step.anchor} nth ${step.nth}" else step.anchor
            is Step.Popup -> step.label
            is Step.Action -> step.id
            is Step.Key -> step.name
            is Step.Open -> step.path
            is Step.WaitFor -> step.what
            else -> ""
        }
        showFieldsFor(stepKind.selectedItem as String)
        loading = false
    }

    private fun kindOf(step: Step): String = when (step) {
        is Step.Open -> "Open"
        is Step.Caret -> "Caret"
        is Step.Select -> "Select"
        is Step.Scroll -> "Scroll"
        is Step.Glide -> "Glide"
        is Step.Click -> if (step.ctrl) "CtrlClick" else "Click"
        is Step.Popup -> "Popup"
        is Step.Action -> "Action"
        is Step.Key -> "Key"
        is Step.Sleep -> "Sleep"
        is Step.WaitFor -> "WaitFor"
    }

    /** Enables only the fields a command actually carries, so nothing reads as editable in vain. */
    private fun showFieldsFor(kind: String) {
        stepDuration.isEnabled = kind in setOf("Sleep", "Glide", "WaitFor")
        stepLine.isEnabled = kind in setOf("Caret", "Select", "Scroll")
        stepText.isEnabled = kind in setOf("Caret", "Select", "Popup", "Action", "Key", "Open", "WaitFor")
        stepText.toolTipText = TEXT_HINTS[kind]
    }

    /**
     * Builds a step of the selected kind from the fields.
     *
     * Changing the command is a conversion rather than an edit, so a field the new kind does not use
     * is simply dropped; keeping it would mean carrying invisible state the tape cannot express.
     */
    private fun stepFromFields(): Step {
        val ms = stepDuration.value as Int
        val line = stepLine.value as Int
        val raw = stepText.text.trim()
        // "Baz nth 2" in one field, so occurrence is editable without another spinner.
        val nthAt = raw.indexOf(" nth ")
        val text = if (nthAt >= 0) raw.substring(0, nthAt).trim() else raw
        val nth = if (nthAt >= 0) raw.substring(nthAt + 5).trim().toIntOrNull() ?: 1 else 1

        return when (stepKind.selectedItem as String) {
            "Open" -> Step.Open(text)
            "Caret" -> Step.Caret(line, text, nth)
            "Select" -> Step.Select(line, text, nth)
            "Scroll" -> Step.Scroll(line)
            "Glide" -> Step.Glide(ms)
            "Click" -> Step.Click(ctrl = false)
            "CtrlClick" -> Step.Click(ctrl = true)
            "Popup" -> Step.Popup(text)
            "Action" -> Step.Action(text)
            "Key" -> Step.Key(text.ifBlank { "Escape" })
            "Sleep" -> Step.Sleep(ms)
            "WaitFor" -> Step.WaitFor(text.ifBlank { "popup" }, ms)
            else -> error("unknown command")
        }
    }

    /** Inserts a new step after the selection, or at the end when nothing is selected. */
    private fun addNewStep() {
        val file = currentFile() ?: return
        val document = com.intellij.openapi.fileEditor.FileDocumentManager.getInstance().getDocument(file)
            ?: return
        val step = runCatching { stepFromFields() }.getOrElse {
            setStatus(it.message ?: "Cannot build that command", error = true)
            return
        }
        val after = selectedSourceLine() ?: parsed?.stepLines?.lastOrNull() ?: document.lineCount
        val lines = document.text.lines().toMutableList()
        val at = after.coerceIn(0, lines.size)
        lines.add(at, TapeWriter.renderStep(step))

        WriteCommandAction.writeCommandAction(project)
            .withName("Add Demo Tape Step")
            .run<RuntimeException> {
                document.setText(lines.joinToString("\n"))
                PsiDocumentManager.getInstance(project).commitDocument(document)
            }
        val index = stepList.selectedIndex
        load()
        if (steps.size > 0) stepList.selectedIndex = (index + 1).coerceIn(0, steps.size - 1)
        setStatus("Added ${TapeWriter.renderStep(step)}")
    }

    private fun selectedStep(): Step? = parsed?.steps?.getOrNull(stepList.selectedIndex)

    private fun selectedSourceLine(): Int? = parsed?.stepLines?.getOrNull(stepList.selectedIndex)

    /** Rebuilds the selected step from the fields, command included, and writes it back. */
    private fun applySelectedStep() {
        if (selectedStep() == null) return
        val updated = runCatching { stepFromFields() }.getOrElse {
            setStatus(it.message ?: "Cannot build that command", error = true)
            return
        }
        editTape { source, line -> TapeWriter.replaceStep(source, line, updated) }
        setStatus("Wrote ${TapeWriter.renderStep(updated)}")
    }

    private fun moveSelected(delta: Int) {
        val index = stepList.selectedIndex
        if (index < 0) return
        editTape { text, line -> TapeWriter.moveStep(text, line, delta) }
        if (steps.size > 0) {
            stepList.selectedIndex = (index + delta).coerceIn(0, steps.size - 1)
        }
    }

    /** Applies an edit to the selected step and writes the file. */
    private fun editTape(edit: (String, Int) -> String) {
        val file = currentFile() ?: return
        val line = selectedSourceLine() ?: return
        val document = com.intellij.openapi.fileEditor.FileDocumentManager.getInstance().getDocument(file)
            ?: return
        val updated = edit(document.text, line)
        if (updated == document.text) return

        WriteCommandAction.writeCommandAction(project)
            .withName("Edit Demo Tape Step")
            .run<RuntimeException> {
                document.setText(updated)
                PsiDocumentManager.getInstance(project).commitDocument(document)
            }
        load()
    }

    /** Writes the framing controls back into the tape file, as tape source. */
    private fun save() {
        val file = currentFile() ?: return
        val text = currentText() ?: return
        val existing = try {
            TapeParser.parse(text).settings
        } catch (e: Exception) {
            setStatus("Not saving: tape does not parse (${e.message})", error = true)
            return
        }

        val crop = try {
            cropFromControls()
        } catch (e: Exception) {
            setStatus(e.message ?: "Bad framing argument", error = true)
            return
        }

        val updated = existing.copy(
            crop = crop,
            padding = (padding.value as Int),
            width = (width.value as Int),
            framerate = (framerate.value as Int),
            cursor = cursor.isSelected,
            tooltips = tooltips.isSelected,
            snap = snap.isSelected,
        )
        if (updated == existing) return

        val document = com.intellij.openapi.fileEditor.FileDocumentManager.getInstance().getDocument(file)
        if (document == null) {
            setStatus("Cannot edit ${file.name}", error = true)
            return
        }
        val newText = TapeWriter.apply(document.text, updated)
        if (newText == document.text) return

        WriteCommandAction.writeCommandAction(project)
            .withName("Update Demo Tape Framing")
            .run<RuntimeException> {
                document.setText(newText)
                PsiDocumentManager.getInstance(project).commitDocument(document)
            }
        setStatus("Wrote framing into ${file.name}")
        load()
    }

    private fun cropFromControls(): Crop {
        val arg = cropArg.text.trim()
        return when (val mode = cropMode.selectedItem) {
            "window" -> Crop.Window
            "editor" -> Crop.Editor
            "fit" -> Crop.Fit
            "component" -> Crop.Component(
                arg.ifEmpty { throw IllegalArgumentException("Component needs a name, e.g. Project") })
            // Reuse the parser rather than a second reader here, so the panel cannot accept
            // something the tape format would reject.
            "region" -> TapeParser.parse("Set Crop region $arg").settings.crop
            "follow mouse" -> TapeParser.parse("Set Crop follow mouse $arg").settings.crop
            "follow caret" -> TapeParser.parse("Set Crop follow caret $arg").settings.crop
            else -> throw IllegalArgumentException("unknown crop mode $mode")
        }
    }

    /**
     * Begins watching the IDE. The panel deliberately does not take focus afterwards: the point
     * is to use the editor normally, and a recorder that stole focus would record itself.
     */
    private fun startRecording() {
        recorder.start()
        recordButton.isEnabled = false
        runButton.isEnabled = false
        stopButton.isEnabled = true
        setStatus("Recording. Use the IDE as you would in the demo, then press Stop.")
    }

    /** Stops watching and writes the tape next to the current one. */
    private fun stopRecording() {
        val settings = runCatching { TapeParser.parse(currentText().orEmpty()).settings }
            .getOrDefault(TapeSettings(outputs = listOf("docs/demo.gif")))
        val text = recorder.stop(settings)

        recordButton.isEnabled = true
        runButton.isEnabled = true
        stopButton.isEnabled = false

        val dir = currentFile()?.parent
            ?: com.intellij.openapi.vfs.LocalFileSystem.getInstance()
                .refreshAndFindFileByPath(project.basePath ?: return)
            ?: return

        WriteCommandAction.writeCommandAction(project)
            .withName("Write Recorded Tape")
            .run<RuntimeException> {
                val name = uniqueName(dir)
                val file = dir.createChildData(this, name)
                file.setBinaryContent(text.toByteArray(Charsets.UTF_8))
                FileEditorManager.getInstance(project).openFile(file, true)
                setStatus("Wrote $name with ${recorder.stepCount} steps. Tidy the Sleep lines.")
            }
        refreshTapes()
    }

    private fun uniqueName(dir: VirtualFile): String {
        var n = 1
        while (dir.findChild("recorded-$n.tape") != null) n++
        return "recorded-$n.tape"
    }

    private fun run() {
        val file = currentFile() ?: return
        val tape = try {
            TapeParser.parse(currentText().orEmpty())
        } catch (e: Exception) {
            TapeRunner.notify(project, NotificationType.ERROR, "Cannot read ${file.name}: ${e.message}")
            return
        }
        if (tape.steps.isEmpty()) {
            TapeRunner.notify(project, NotificationType.WARNING, "${file.name} has no steps.")
            return
        }

        // Resolve ffmpeg before the take rather than during it: finding out at render time that
        // there is no encoder means the performance was for nothing.
        val resolved = if (tape.settings.outputs.isEmpty()) tape.settings.ffmpeg
        else Ffmpeg.ensure(project, tape.settings.ffmpeg) ?: return
        val ready = tape.copy(settings = tape.settings.copy(ffmpeg = resolved))

        runButton.isEnabled = false
        setStatus("Running ${file.name}")
        TapeRunner.launch(project, file.name, ready) {
            ApplicationManager.getApplication().invokeLater {
                runButton.isEnabled = true
                setStatus("Finished ${file.name}")
            }
        }
    }

    private fun setStatus(message: String, error: Boolean = false) {
        status.text = message
        status.foreground = if (error) JBColor.RED else JBColor.GRAY
    }

    private companion object {
        val STEP_KINDS = arrayOf(
            "Open", "Caret", "Select", "Scroll", "Glide", "Click", "CtrlClick",
            "Popup", "Action", "Key", "Sleep", "WaitFor")
        val TEXT_HINTS = mapOf(
            "Open" to "Path, relative to the project or absolute",
            "Caret" to "Anchor text; add  nth 2  to pick a later occurrence on the line",
            "Select" to "Anchor text to select; add  nth 2  for a later occurrence",
            "Scroll" to "No text; set the line instead",
            "Popup" to "Row label, matched exactly first then loosely",
            "Action" to "IDE action id, for example GotoDeclaration or Back",
            "Key" to "Escape, Enter, Tab, Up, Down, Left, Right",
            "WaitFor" to "popup or editor",
        )
        val CROP_MODES = arrayOf(
            "window", "editor", "component", "region", "fit", "follow mouse", "follow caret")
        val MODES_WITH_ARG = setOf("component", "region", "follow mouse", "follow caret")
        val ARG_HINTS = mapOf(
            "window" to "No argument",
            "editor" to "No argument",
            "fit" to "No argument; framed from the tape's own Caret targets",
            "component" to "A tool window id, or editor / editors / content",
            "region" to "X,Y WxH  for example  360,160 1030x600",
            "follow mouse" to "WxH ease Nms  for example  840x390 ease 350ms",
            "follow caret" to "WxH ease Nms  for example  950x415 ease 350ms",
        )
    }
}
